version: 1
update_configs:
- package_manager: "java:maven" # REQUIRED
  directory: "/" # REQUIRED
  update_schedule: "daily" # REQUIRED
  target_branch: "master"
  default_reviewers:
  - "RomanJRW"
  default_labels:
  - "dependencies"
  allowed_updates:
  - match:
      update_type: "security"
      
